{
 "title": "Logging",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "review_stars", "query": "1, 2, 3, 4, 5" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Logging Statements by Level",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 1 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (level) (rate({app=\"dev-prod-o11y-parity\"} | json [1m])) * 60",
     "legendFormat": "{{detected_level}}"
    }
   ]
  },
  {
   "title": "Level Distribution",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (level) (count_over_time({app=\"dev-prod-o11y-parity\"} | json [$__range]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  { "title": "Reviews", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Reviews received",
   "type": "table",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 11 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"dev-prod-o11y-parity\"} |= \"Received new review\" | json | review_stars=~\"$review_stars\""
    }
   ]
  },
  {
   "title": "Review Star Distribution",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (review_stars) (count_over_time({app=\"dev-prod-o11y-parity\"} |= \"Received new review\" | json [$__range]))",
     "legendFormat": "{{review_stars}} ⭐"
    }
   ]
  },
  { "title": "Raw Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Raw Logs",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"dev-prod-o11y-parity\"} | json | line_format \"{{alignLeft 5 .level}} --- {{alignLeft 32 .logger_name}}: {{.message}}\""
    }
   ]
  }
 ]
}